### ISSUE TITLE
No Operating System - No Images Available 

### ISSUE THREAD

**Issue by cjbischoff** [StefanScherer/packer-windows#20] opened 2016-12-16 13:08 UTC
Performing - hangs with the vmware fusion screen

![image](https://cloud.githubusercontent.com/assets/126409/21263803/00161be0-c356-11e6-81db-499015944bbd.png)

❯❯❯ packer build --only=vmware-iso windows_2016.json                                                                                                                                                                                                   ⏎ ✱ (git:my)
vmware-iso output will be in this color.

==> vmware-iso: Downloading or copying ISO
    vmware-iso: Downloading or copying: http://care.dlservice.microsoft.com/dl/download/1/6/F/16FA20E6-4662-482A-920B-1A45CF5AAE3C/14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO
==> vmware-iso: Creating floppy disk...
    vmware-iso: Copying files flatly from floppy_files
    vmware-iso: Copying file: ./answer_files/2016/Autounattend.xml
    vmware-iso: Copying file: ./floppy/WindowsPowershell.lnk
    vmware-iso: Copying file: ./floppy/PinTo10.exe
    vmware-iso: Copying file: ./scripts/disable-screensaver.ps1
    vmware-iso: Copying file: ./scripts/disable-winrm.ps1
    vmware-iso: Copying file: ./scripts/enable-winrm.ps1
    vmware-iso: Copying file: ./scripts/microsoft-updates.bat
    vmware-iso: Copying file: ./scripts/win-updates.ps1
    vmware-iso: Done copying files from floppy_files
    vmware-iso: Collecting paths from floppy_dirs
    vmware-iso: Resulting paths from floppy_dirs : []
    vmware-iso: Done copying paths from floppy_dirs
==> vmware-iso: Creating virtual machine disk
==> vmware-iso: Building and writing VMX file
==> vmware-iso: Starting virtual machine...
==> vmware-iso: Waiting 2m0s for boot...
==> vmware-iso: Connecting to VM via VNC
==> vmware-iso: Typing the boot command over VNC...
==> vmware-iso: Waiting for WinRM to become available...

**Comment by cjbischoff** [comment] 2016-12-16 13:09
Further poking around I found this -> http://jontriphan.com/windows-8-error-there-are-no-images-available-on-wmware/

Basically I disable the floppy and restart and it works, but it breaks auto-build since you are using the floppy

**Comment by StefanScherer** [comment] 2016-12-16 15:59
@cjbischoff Just tried `packer build --only=vmware-iso windows_2016.json` and it doesn't hang here.
I'm using packer 0.12.0, Fusion Pro 8.5.3, but it should work without Pro as well.

You could try with debug output

```
PACKER_LOG=debug packer build --only=vmware-iso windows_2016.json` and link a gist of it.

**Comment by cjbischoff** [comment] 2016-12-16 16:43
@StefanScherer Ok the debug is nice 

```
==> vmware-iso: Waiting for WinRM to become available...
2016/12/16 09:40:07 packer: 2016/12/16 09:40:07 Lookup up IP information...
2016/12/16 09:40:07 packer: 2016/12/16 09:40:07 DHCP leases path: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
2016/12/16 09:40:07 packer: 2016/12/16 09:40:07 IP lookup failed: open /var/db/vmware/vmnet-dhcpd-vmnet8.leases: no such file or directory
```

So something is up with network connectivity.

During your builds is your network set to Share with Mac or Private to Mac?

**Comment by StefanScherer** [comment] 2016-12-16 19:47
I can see the same debug output while the guest does not have setup the network interface. The message still appears while the win-update script searches for the first Windows Updates.

I can see the following settings in the `output*/*.vmx` file

```
ethernet0.addresstype = "generated"
ethernet0.bsdname = "en0"
ethernet0.connectiontype = "nat"
ethernet0.displayname = "Ethernet"
ethernet0.linkstatepropagation.enable = "FALSE"
ethernet0.pcislotnumber = "33"
ethernet0.present = "TRUE"
ethernet0.virtualdev = "e1000"
ethernet0.wakeonpcktrcv = "FALSE"
ethernet0.generatedAddress = "00:0c:29:ed:de:30"
ethernet0.generatedAddressOffset = "0"
```

Just the normal settings.

**Comment by StefanScherer** [comment] 2017-01-13 20:51
@cjbischoff Have you made any progress?

**Comment by StefanScherer** [comment] 2017-01-28 15:05
I can reproduce the problem, but with the Windows 10 Insider 15002 ISO file. Seems that this ISO can't be used with the autounattend.xml as there is no selection needed.
OK, it seems to work - at least it's getting files ready for installation by removing the ProductKey and the InstallFrom sections in the autounattend.xml.
Do you use eg. the Win2016 essentials ISO file?

**Comment by StefanScherer** [comment] 2017-02-02 13:47
Closing this as it seems to be a problem with the ISO itself. Rebuilt two boxes yesterday with latest ISO works. But if you still have problem, don't hesitate to reopen.

**Closed by StefanScherer** 2017-02-02 13:47 UTC
